name: CI Pipeline
on:
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Compile docker for x86_64
        run: ./compile-docker.sh build x86_64
      - name: Compile docker for aarch64
        run: ./compile-docker.sh build aarch64
      - name: Compile docker for armv7
        run: ./compile-docker.sh build armv7
      - name: Compile docker for armv6
        run: ./compile-docker.sh build armv6
      - name: Archive tar.xz files
        run: mkdir -p artifacts && mv ./build/out/*.tar.xz artifacts/
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-tarballs
          path: artifacts/
  release:
    needs: build
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: docker-tarballs
          path: artifacts/
      - name: Upload all tar.xz files
        run: |
          for file in artifacts/*.tar.xz; do
            echo "Uploading $file as release asset..."
            gh release upload ${{ github.event.release.tag_name }} "$file" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
